In [3]:
import numpy as np

from gradient_descent import GradientDescent

In [5]:
X_data = np.random.rand((10*15)).reshape(10,15).astype('float32')
# print X_data

In [7]:
gd1 = GradientDescent(m=10, n=15, eta=0.5, numEig=3)

initiliased eigenValues of shape (3,)
initiliased eigenVectors of shape (15, 3)


In [8]:
w,v = gd1.getAllEigenValuesAndVectors(X_data, epsilon=1e-30, max_iteraions=50, validateEpsilon=5)

X_dot_v previousEigenContribution self.objectiveFunction grad_v y updateFunction self.train trained
Getting eigen value and vector # 0
Shape of X_data:  (10, 15)
Number of iterations done:  49
Eigen Value: 37.4786
Eigen Vector:
[ 0.21722624  0.19825378  0.205801    0.27871075  0.34445381  0.32099384
  0.28843579  0.2052312   0.22344074  0.29808384  0.18327773  0.24025789
  0.2648904   0.34213495  0.17075226]
X_dot_v previousEigenContribution self.objectiveFunction grad_v y updateFunction self.train trained
Getting eigen value and vector # 1
Shape of X_data:  (10, 15)
Number of iterations done:  49
Eigen Value: 2.48935
Eigen Vector:
[ 0.06268036  0.42400753  0.37976769 -0.10993089  0.30638289 -0.19838879
  0.11473024 -0.1223332  -0.45693058 -0.03981199  0.40108338 -0.22217263
 -0.09782258 -0.09923037 -0.24209172]
X_dot_v previousEigenContribution self.objectiveFunction grad_v y updateFunction self.train trained
Getting eigen value and vector # 2
Shape of X_data:  (10, 15)
Number of iter

In [9]:
print w
print v

[ 37.47856522   2.48935223   2.20316625]
[[ 0.21722624  0.06268036  0.30626807]
 [ 0.19825378  0.42400753 -0.23292701]
 [ 0.205801    0.37976769  0.07126501]
 [ 0.27871075 -0.10993089 -0.17280355]
 [ 0.34445381  0.30638289  0.17986731]
 [ 0.32099384 -0.19838879  0.04072222]
 [ 0.28843579  0.11473024  0.25354016]
 [ 0.2052312  -0.1223332   0.11581952]
 [ 0.22344074 -0.45693058 -0.24998091]
 [ 0.29808384 -0.03981199 -0.17106286]
 [ 0.18327773  0.40108338 -0.10141265]
 [ 0.24025789 -0.22217263  0.34360874]
 [ 0.2648904  -0.09782258 -0.55181551]
 [ 0.34213495 -0.09923037 -0.11567611]
 [ 0.17075226 -0.24209172  0.40903798]]


In [10]:
w_np,v_np = np.linalg.eigh(np.dot(X_data.T,X_data))
idx = np.argsort(-w_np)
w_np = w_np[idx]
v_np = v_np[:,idx]
# for i in range(DIMENSIONS):
#     print w_np[i]
#     print v_np[:,i]
print w_np.astype('float32')
print v_np.astype('float32')


[  3.74785652e+01   2.48937249e+00   2.20314312e+00   1.36261272e+00
   1.12379670e+00   6.58689201e-01   5.42867661e-01   4.13328201e-01
   2.48995125e-01   6.98108822e-02   5.06017898e-07   2.26031375e-07
   1.37965756e-07  -2.00754783e-07  -3.20158335e-07]
[[  2.17226237e-01   6.00774996e-02  -3.06858391e-01  -7.95260351e-03
   -3.14708859e-01  -3.23834717e-02   6.02333784e-01  -1.72415022e-02
   -1.45817861e-01  -1.67185783e-01  -7.12614208e-02  -2.73743063e-01
   -2.67190576e-01  -4.20354277e-01  -1.20285526e-01]
 [  1.98253781e-01   4.25965697e-01   2.28851676e-01   3.87286916e-02
   -1.61140904e-01   2.08486050e-01   6.49515614e-02  -2.97389537e-01
   -1.72240585e-02   1.55469894e-01  -4.50695902e-02   2.60876626e-01
   -2.98549160e-02  -1.82382718e-01   6.59221828e-01]
 [  2.05800995e-01   3.79145592e-01  -7.49052092e-02   2.38295019e-01
    1.03015259e-01  -1.18482217e-01   2.09559783e-01   5.88209689e-01
    5.96754514e-02  -3.09506506e-01  -1.48823768e-01   3.35774124e-01
  